services:
  - type: web
    name: financetracker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn financetracker.wsgi:application